[build]
  command = "npm run build"
  publish = "build"
  base = ""

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
